# Generated by Django 6.0.3 on 2026-04-14 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la sección (ej: A, B, VIP)', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('ASIGNADOS', 'Asignados'), ('ROTATIVOS', 'Rotativos')], default='ROTATIVOS', help_text='Tipo de espacios en esta sección', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la sección', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivada, no se muestra en el mapa')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'secciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número/código del espacio (ej: A1, A2, B1)', max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='LIBRE', help_text='Estado actual del espacio', max_length=20)),
                ('posicion_fila', models.IntegerField(default=0, help_text='Fila en el mapa visual (0-indexado)')),
                ('posicion_columna', models.IntegerField(default=0, help_text='Columna en el mapa visual (0-indexado)')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no se puede usar')),
                ('notas', models.TextField(blank=True, help_text='Notas o comentarios sobre este espacio', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('seccion', models.ForeignKey(help_text='Sección a la que pertenece este espacio', on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='espacios.seccion')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'db_table': 'espacios',
                'ordering': ['seccion', 'numero'],
            },
        ),
    ]
