# Generated by Django 6.0.3 on 2026-04-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa del vehículo (ej: ABC-123)', max_length=20)),
                ('tipo_vehiculo', models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta')], default='AUTO', help_text='Tipo de vehículo', max_length=20)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de entrada (automática)')),
                ('fecha_salida', models.DateTimeField(blank=True, help_text='Fecha y hora de salida', null=True)),
                ('tiempo_minutos', models.IntegerField(blank=True, help_text='Tiempo total en minutos', null=True)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa total a pagar en Bs.', max_digits=8, null=True)),
                ('horario_entrada', models.CharField(choices=[('DIURNO', 'Diurno'), ('NOCTURNO', 'Nocturno')], help_text='Horario de entrada (diurno/nocturno)', max_length=20)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='EN_CURSO', help_text='Estado del registro', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas u observaciones adicionales', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('espacio', models.ForeignKey(help_text='Espacio asignado a este vehículo', on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='espacios.espacio')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'db_table': 'registros',
                'ordering': ['-fecha_entrada'],
                'indexes': [models.Index(fields=['placa'], name='registros_placa_57be48_idx'), models.Index(fields=['estado'], name='registros_estado_a9de34_idx'), models.Index(fields=['fecha_entrada'], name='registros_fecha_e_aea730_idx')],
            },
        ),
    ]
