# Generated by Django 6.0.3 on 2026-05-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primera_hora_diurno', models.DecimalField(decimal_places=2, default=9.0, help_text='Bs. por la primera hora en horario diurno', max_digits=6)),
                ('hora_adicional_diurno', models.DecimalField(decimal_places=2, default=2.0, help_text='Bs. por cada hora adicional en horario diurno', max_digits=6)),
                ('primera_hora_nocturno', models.DecimalField(decimal_places=2, default=12.0, help_text='Bs. por la primera hora en horario nocturno', max_digits=6)),
                ('hora_adicional_nocturno', models.DecimalField(decimal_places=2, default=5.0, help_text='Bs. por cada hora adicional en horario nocturno', max_digits=6)),
                ('hora_inicio_diurno', models.PositiveSmallIntegerField(default=6, help_text='Hora en que empieza el horario diurno (0-23). Ej: 6 = 6:00 AM')),
                ('hora_fin_diurno', models.PositiveSmallIntegerField(default=18, help_text='Última hora del horario diurno (0-23). Ej: 18 = válido hasta las 18:59')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
    ]
