# Generated by Django 6.0.3 on 2026-05-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='tarifa_hora_adicional_diurno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='tarifa_hora_adicional_nocturno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='tarifa_hora_fin_diurno',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='tarifa_hora_inicio_diurno',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='tarifa_primera_hora_diurno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='tarifa_primera_hora_nocturno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
